name: freecell
description: 'A classic FreeCell solitaire game built with Flutter'
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  logger: ^2.5.0
  soundpool: ^2.4.1
  intl: ^0.20.0
  file_picker: ^8.0.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
    - family: Suits
      fonts:
        - asset: assets/icons/Suits.ttf
  assets:
    - assets/flick.mp3
    - assets/winSounds/
flutter_icons:
  android: true
  image_path: 'assets/icon.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/icon.png'
